spring:
  application:
    name: catapiintegration
server:
  port: 8099
cat:
  api:
    base-url: ${CAT_API_BASE_URL:http://localhost:8081}
    key: ${CAT_API_KEY:demo-secret-key}
    max-rps: ${CAT_API_MAX_RPS:1}

logging:
  level:
    net.proselyte.catapiintegration: DEBUG